### ISSUE TITLE
Operational issues

### ISSUE THREAD

**Issue by zhangyiyi2** [lghupan/Starfish#2]
Hello, do you have a more accurate version of Python and the versions of each library in the requirements file? I ran the demo_size_quality.ipynb, but reporting an error~~

![1704377813322](https://github.com/lghupan/Starfish/assets/92798580/699d900e-9fe6-4d37-932c-51603fc980e3)

**Comment by lghupan** [comment]
Unfortunately I do not have a specification for the Python/Tensorflow versions, but these are warnings rather than errors in your screenshot. Were you able to continue running the next code block?

**Comment by zhangyiyi2** [comment]
Aha? I see~ but I did get an error when I continued to run the third module~ as shown in the figure below, please take a look~
![微信图片_20240105085728](https://github.com/lghupan/Starfish/assets/92798580/ed395633-d52f-4258-876b-ffb8b6d6b078)

**Comment by lghupan** [comment]
Could you send me the entire ipynb file?

**Comment by zhangyiyi2** [comment]
Sorry to trouble you. This is the entire file, thank you very much.
[ipynb file.zip](https://github.com/lghupan/Starfish/files/13842426/ipynb.file.zip)

**Comment by lghupan** [comment]
Thanks for the file. Using Python3.7 (with pip or conda) and install the latest requirements.txt solved the problem for me.

**Comment by zhangyiyi2** [comment]
With your suggestions and modifications made to some versions of the libraries, the ipynb files can run as expected now. Thank you very much for your guidance and efforts. If there are any issues, I may continue to disturb you~ Thank you very much!
