### ISSUE TITLE
Question of NAS

### ISSUE THREAD

**Issue by menger02** [lghupan/Starfish#4]
Hello, I'm very sorry to disturb you. I am very interested in your project and would like to reproduce it. But I couldn't find the code for NAS(Network Architecture Search). Can you provide the corresponding code?

**Comment by lghupan** [comment]
Hi @menger02, thank you for reaching out. Unfortunately, I couldn't find the corresponding part for NAS. However, it should be straightforward to implement, and I'm happy to assist if you encounter any problems.
